# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Eric Escalante'
tagline:             'Blogging gingerly'
description:         'A simple blog about software development, and being coy about it.'
url:                 http://ericescalante.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Eric Escalante
  url:               https://twitter.com/peluchio

# Custom vars
version:             1.0.0

gems:
  - jekyll-sitemap